/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as CompleteRouteImport } from './routes/complete';
import { Route as IndexRouteImport } from './routes/index';
import { Route as WordTaskRouteImport } from './routes/word/task';
import { Route as WordPracticeRouteImport } from './routes/word/practice';
import { Route as WordInstructionsRouteImport } from './routes/word/instructions';
import { Route as ClusterTaskRouteImport } from './routes/cluster/task';
import { Route as ClusterPracticeRouteImport } from './routes/cluster/practice';
import { Route as ClusterInstructionsRouteImport } from './routes/cluster/instructions';

const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const WordTaskRoute = WordTaskRouteImport.update({
  id: '/word/task',
  path: '/word/task',
  getParentRoute: () => rootRouteImport,
} as any);
const WordPracticeRoute = WordPracticeRouteImport.update({
  id: '/word/practice',
  path: '/word/practice',
  getParentRoute: () => rootRouteImport,
} as any);
const WordInstructionsRoute = WordInstructionsRouteImport.update({
  id: '/word/instructions',
  path: '/word/instructions',
  getParentRoute: () => rootRouteImport,
} as any);
const ClusterTaskRoute = ClusterTaskRouteImport.update({
  id: '/cluster/task',
  path: '/cluster/task',
  getParentRoute: () => rootRouteImport,
} as any);
const ClusterPracticeRoute = ClusterPracticeRouteImport.update({
  id: '/cluster/practice',
  path: '/cluster/practice',
  getParentRoute: () => rootRouteImport,
} as any);
const ClusterInstructionsRoute = ClusterInstructionsRouteImport.update({
  id: '/cluster/instructions',
  path: '/cluster/instructions',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/complete': typeof CompleteRoute;
  '/cluster/instructions': typeof ClusterInstructionsRoute;
  '/cluster/practice': typeof ClusterPracticeRoute;
  '/cluster/task': typeof ClusterTaskRoute;
  '/word/instructions': typeof WordInstructionsRoute;
  '/word/practice': typeof WordPracticeRoute;
  '/word/task': typeof WordTaskRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/complete': typeof CompleteRoute;
  '/cluster/instructions': typeof ClusterInstructionsRoute;
  '/cluster/practice': typeof ClusterPracticeRoute;
  '/cluster/task': typeof ClusterTaskRoute;
  '/word/instructions': typeof WordInstructionsRoute;
  '/word/practice': typeof WordPracticeRoute;
  '/word/task': typeof WordTaskRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/complete': typeof CompleteRoute;
  '/cluster/instructions': typeof ClusterInstructionsRoute;
  '/cluster/practice': typeof ClusterPracticeRoute;
  '/cluster/task': typeof ClusterTaskRoute;
  '/word/instructions': typeof WordInstructionsRoute;
  '/word/practice': typeof WordPracticeRoute;
  '/word/task': typeof WordTaskRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/complete'
    | '/cluster/instructions'
    | '/cluster/practice'
    | '/cluster/task'
    | '/word/instructions'
    | '/word/practice'
    | '/word/task';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/complete'
    | '/cluster/instructions'
    | '/cluster/practice'
    | '/cluster/task'
    | '/word/instructions'
    | '/word/practice'
    | '/word/task';
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/cluster/instructions'
    | '/cluster/practice'
    | '/cluster/task'
    | '/word/instructions'
    | '/word/practice'
    | '/word/task';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CompleteRoute: typeof CompleteRoute;
  ClusterInstructionsRoute: typeof ClusterInstructionsRoute;
  ClusterPracticeRoute: typeof ClusterPracticeRoute;
  ClusterTaskRoute: typeof ClusterTaskRoute;
  WordInstructionsRoute: typeof WordInstructionsRoute;
  WordPracticeRoute: typeof WordPracticeRoute;
  WordTaskRoute: typeof WordTaskRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete': {
      id: '/complete';
      path: '/complete';
      fullPath: '/complete';
      preLoaderRoute: typeof CompleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/word/task': {
      id: '/word/task';
      path: '/word/task';
      fullPath: '/word/task';
      preLoaderRoute: typeof WordTaskRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/word/practice': {
      id: '/word/practice';
      path: '/word/practice';
      fullPath: '/word/practice';
      preLoaderRoute: typeof WordPracticeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/word/instructions': {
      id: '/word/instructions';
      path: '/word/instructions';
      fullPath: '/word/instructions';
      preLoaderRoute: typeof WordInstructionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cluster/task': {
      id: '/cluster/task';
      path: '/cluster/task';
      fullPath: '/cluster/task';
      preLoaderRoute: typeof ClusterTaskRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cluster/practice': {
      id: '/cluster/practice';
      path: '/cluster/practice';
      fullPath: '/cluster/practice';
      preLoaderRoute: typeof ClusterPracticeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cluster/instructions': {
      id: '/cluster/instructions';
      path: '/cluster/instructions';
      fullPath: '/cluster/instructions';
      preLoaderRoute: typeof ClusterInstructionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  ClusterInstructionsRoute: ClusterInstructionsRoute,
  ClusterPracticeRoute: ClusterPracticeRoute,
  ClusterTaskRoute: ClusterTaskRoute,
  WordInstructionsRoute: WordInstructionsRoute,
  WordPracticeRoute: WordPracticeRoute,
  WordTaskRoute: WordTaskRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
