/**
 * Zod schemas shared between client and server.
 *
 * These validate the cross-cutting request contracts from contracts/api.md:
 *  - the `X-Participant-Id` header (a UUID v4, matching `crypto.randomUUID()` output, R3/FR-012)
 *  - the `POST /api/responses` request body (`SubmitRequest`)
 *  - the `Selection` value object
 *
 * Server-only Study/ground-truth schemas live in `server/src/services/studyLoader.ts`, never here.
 */

import { z } from 'zod';
import type { Selection, SubmitRequest, WelcomeContent } from './types';

/**
 * Anonymous participant id: a UUID v4 generated by the client on first visit (FR-012, R3).
 * Validating the format server-side prevents path traversal when the id is used as a storage
 * path segment (storage.md "Access model").
 */
export const ParticipantIdSchema = z.uuidv4();

/** Returns true iff `value` is a well-formed participant id (UUID v4). */
export function isValidParticipantId(value: unknown): value is string {
  return ParticipantIdSchema.safeParse(value).success;
}

/**
 * Optional top-level `study.welcome` (storage.md, FR-012). Its content is a non-empty string when
 * present; the whole block is optional, and its absence tells the server to supply the localized
 * built-in default. Researcher-authored copy is stored/displayed verbatim (never translated, FR-015).
 */
export const WelcomeContentSchema: z.ZodType<WelcomeContent> = z.object({
  content: z.string().min(1),
});

/** A selection is exactly one chosen candidate (FR-002; the `cant_tell` variant was removed, FR-006). */
export const SelectionSchema: z.ZodType<Selection> = z.object({
  kind: z.literal('candidate'),
  value: z.string().min(1),
});

/** Body of `POST /api/responses` (contracts/api.md). `itemId` is a real itemId or a practiceId. */
export const SubmitRequestSchema: z.ZodType<SubmitRequest> = z.object({
  itemId: z.string().min(1),
  taskType: z.enum(['word', 'cluster']),
  selection: SelectionSchema,
  timeTakenMs: z.number().int().nonnegative().optional(),
});
